# Generated by Django 6.0.1 on 2026-01-30 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Mesin')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Mesin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='machine_images/', verbose_name='Foto Mesin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Kode Barang')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Sparepart')),
                ('category', models.CharField(choices=[('Elektrikal', 'Elektrikal'), ('Mekanikal', 'Mekanikal'), ('Hidrolik', 'Hidrolik'), ('Pneumatik', 'Pneumatik'), ('Konsumabel', 'Konsumabel')], max_length=50, verbose_name='Kategori')),
                ('stock', models.IntegerField(default=0, verbose_name='Stok Saat Ini')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Min. Stok (Peringatan)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sparepart_images/', verbose_name='Foto Sparepart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.machine', verbose_name='Mesin')),
            ],
        ),
    ]
