# Generated by Django 6.0.1 on 2026-01-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='lokasi_drawing',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lokasi Drawing'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='lokasi_penyimpanan',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lokasi Penyimpanan'),
        ),
    ]
