# Generated by Django 6.0.1 on 2026-01-30 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sparepart_lokasi_drawing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine', verbose_name='Mesin'),
        ),
    ]
