# Generated by Django 6.0.1 on 2026-02-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_sparepart_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalPreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_jadwal', models.DateField(verbose_name='Tanggal Jadwal')),
                ('keterangan', models.TextField(verbose_name='Keterangan Pekerjaan')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Selesai', 'Selesai')], default='Pending', max_length=20)),
                ('teknisi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Teknisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine', verbose_name='Mesin')),
            ],
        ),
    ]
