# Generated by Django 6.0.1 on 2026-02-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_jadwalpreventive'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalpreventive',
            name='jenis_maintenance',
            field=models.CharField(choices=[('Internal', 'Internal'), ('MTC', 'MTC')], default='Internal', max_length=20, verbose_name='Jenis Maintenance'),
        ),
        migrations.AlterField(
            model_name='jadwalpreventive',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selesai', 'Selesai')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
