# Generated by Django 6.0.1 on 2026-02-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_jadwalpreventive_jenis_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalpreventive',
            name='jenis_maintenance',
            field=models.CharField(choices=[('External', 'External'), ('MTC', 'MTC')], default='Internal', max_length=20, verbose_name='Jenis Maintenance'),
        ),
    ]
