# Generated by Django 6.0.1 on 2026-02-13 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_jadwalpreventive_jenis_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='min_stock',
            field=models.IntegerField(default=1, verbose_name='Min. Stok (Peringatan)'),
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Perbaikan')),
                ('waktu_pengerjaan', models.CharField(help_text='Contoh: 2 Jam', max_length=100, verbose_name='Waktu Pengerjaan')),
                ('penyebab', models.TextField(verbose_name='Penyebab')),
                ('tindakan', models.TextField(verbose_name='Tindakan Perbaikan')),
                ('jenis_trouble', models.CharField(choices=[('Mekanikal', 'Mekanikal'), ('Elektrikal', 'Elektrikal'), ('Hidrolik', 'Hidrolik'), ('Pneumatik', 'Pneumatik'), ('Operasional', 'Operasional'), ('Lainnya', 'Lainnya')], max_length=50, verbose_name='Jenis Trouble')),
                ('pic', models.CharField(max_length=100, verbose_name='Nama PIC (Teknisi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine', verbose_name='Nama Mesin')),
                ('sparepart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sparepart', verbose_name='Sparepart yang Dipakai')),
            ],
        ),
    ]
