# Generated by Django 6.0.1 on 2026-02-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_machine_code_alter_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='kerusakan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
