# Generated by Django 6.0.1 on 2026-02-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_breakdown_kerusakan'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='breakdown_photos/'),
        ),
    ]
