# Generated by Django 6.0.1 on 2026-02-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_breakdown_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='breakdown_images/'),
        ),
    ]
