# Generated by Django 6.0.1 on 2026-02-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_breakdown_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nama Sparepart'),
        ),
    ]
