# Generated by Django 6.0.1 on 2026-06-29 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_membermtc_alter_machine_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermtc',
            options={'ordering': ['nama'], 'verbose_name': 'Member Maintenance', 'verbose_name_plural': 'Member Maintenance'},
        ),
        migrations.CreateModel(
            name='Kaizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tema', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('Safety', 'Safety'), ('Quality', 'Quality'), ('Cost', 'Cost'), ('Delivery', 'Delivery'), ('Productivity', 'Productivity'), ('Environment', 'Environment')], max_length=30)),
                ('kondisi', models.TextField()),
                ('rencana', models.TextField()),
                ('target_selesai', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Progress', 'Progress'), ('Finish', 'Finish')], default='Open', max_length=20)),
                ('foto_before', models.ImageField(blank=True, null=True, upload_to='kaizen/before/')),
                ('foto_after', models.ImageField(blank=True, null=True, upload_to='kaizen/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mesin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine')),
                ('pic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.membermtc')),
            ],
        ),
    ]
