# Generated by Django 6.0.1 on 2026-02-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_machine_name_alter_sparepart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nama Sparepart'),
        ),
    ]
